# Generated by Django 3.1.5 on 2021-01-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210120_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('comment_txt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.comment')),
            ],
        ),
    ]
