# Generated by Django 3.1.5 on 2021-01-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
            ],
        ),
    ]
